name: captafied
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8 # version also pinned in Dockerfile
  - cudatoolkit=11.3.1
  - cudnn=8.3.2
  - pip=21.1.3 # version also pinned in Dockerfile
